version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - sudo yum install git -y
      - git clone --recursive https://vegapatel:Sude3pth!@github.com/vegapatel/aws-codebuild-samples.git
      - ls $PWD/aws-codebuild-samples
    finally:
      - echo This always runs even if the login command fails 
  build:
    commands:
      - npm test
artifacts:
  files:
    - '**/*'
