version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - cd testproject && mkdir test && cd -
      - ls testproject
      - ls testproject/tests
      - ls testproject/tests/test
    finally:
      - echo This always runs even if the login command fails 
  build:
    commands:
      - npm test
artifacts:
  files:
    - '**/*'
